### ISSUE TITLE
Rewrite to support new CTRE drivers

### ISSUE THREAD

**Issue by virtuald** [robotpy/robotpy-ctre#12]
CTRE told me during the 2017 season that they were exploring an approach that would make it easier to create a third-party wrapper around their drivers. I anticipate that a small rewrite of this package will be necessary -- but it should be fairly straightforward to do.

I've reached out to them about the status of the new drivers.

**Comment by virtuald** [comment]
I've confirmed with them that an easier to wrap driver will available this season -- perhaps as early as next week. They said announcements will be made via Twitter/Facebook.

**Comment by virtuald** [comment]
Looks like their framework is out now, needs someone to go look at it and see what needs to be done.

http://www.ctr-electronics.com/control-system/hro.html#product_tabs_technical_resources

**Comment by virtuald** [comment]
I took a brief look, and it looks like not much has changed, so I'll talk to them to see if we can fix it so it isn't as annoying.

**Comment by Twinters007** [comment]
Did you mean to link to the HERO board page?

**Comment by virtuald** [comment]
Yes, if you click on the toolsuite installer link it takes you to the HERO page.

**Comment by virtuald** [comment]
The latest beta installer has the Java sources included, and it looks like it's easier to wrap now. Anyone want to take a crack at it?

**Comment by Twinters007** [comment]
I'll take a look, but can't for sure say I Can dedicate enough time to do it before someone else does

**Comment by virtuald** [comment]
I think the best approach would be trying to autogenerate the bindings from the available header files... as I think they've removed most of the magic from the java code now.

**Comment by ariovistus** [comment]
I can take a crack at this if you don't have time. I assume pygccxml on the cpp include files and something something ctypes

**Comment by virtuald** [comment]
I've already done a large chunk of it, my goal is to entirely autogenerate the motor controller bindings from the C stuff. Check out the autogen branch.

Developing https://github.com/virtuald/header2whatever for codegen, it's pretty neat.

**Comment by ariovistus** [comment]
shall I work on the library part?

**Comment by virtuald** [comment]
The library part? Which part is that? I'm not planning to implement the phoenix framework stuff.

**Comment by virtuald** [comment]
I'll be on gitter for about an hour if you want to yap about this.
