### ISSUE TITLE
Type WPI_MotorSafetyImplem referenced unknown base type frc::MotorSafety

### ISSUE THREAD

**Issue by adam-mcdaniel** [robotpy/robotpy-ctre#122]
![ctre error](https://user-images.githubusercontent.com/28228031/74091385-e2d57580-4a84-11ea-8647-1cfbc30ddb3f.png)

I get this error when I import `WPI_TalonFX`

**Comment by virtuald** [comment]
What version of robotpy-ctre do you have installed?

**Comment by virtuald** [comment]
You would need to have 2020.1.0+ installed for this to work.
