### ISSUE TITLE
CHRP files do not play

### ISSUE THREAD

**Issue by adam-mcdaniel** [robotpy/robotpy-ctre#125]
Whenever I go to play CHRP files, the motors complain the file is too old. I've updated my Phoenix Tuner and my TalonFX firmware, is there something I missed?

**Comment by virtuald** [comment]
I don't have a falcon motor, so no idea. We're wrapping [5.18.1](https://github.com/robotpy/robotpy-ctre/blob/b09361a88e3f6ced90ab0107ca3d59b19586acb6/pyproject.toml#L14), which appears to be the latest version in their vendor json. I suggest that you send CTRE an email and ask them if C++ 5.18.1 supports the CHRP files that you have.

**Comment by virtuald** [comment]
Did you ever figure this out?

**Comment by virtuald** [comment]
I assume this got fixed, let me know if that isn't the case.
