### ISSUE TITLE
Missing CANifier.getPWMInput()

### ISSUE THREAD

**Issue by auscompgeek** [robotpy/robotpy-ctre#127]
https://github.com/robotpy/robotpy-ctre/blob/eda534e7078b5b9c9ec163487b5a1ac898424922/gen/CANifier.yml#L58-L59

This is declared as:
```cpp
ErrorCode GetPWMInput(PWMChannel pwmChannel, double pulseWidthAndPeriod[]);
```
where `pulseWidthAndPeriod` is actually an out-param of length 2.

**Comment by virtuald** [comment]
Fixed.
