### ISSUE TITLE
Configuring WPI_TalonFX results in segmentation fault

### ISSUE THREAD

**Issue by FRC2539** [robotpy/robotpy-ctre#142]
### Problem description

First, all of our motors and encoders have been updated to the latest firmware version (22) via Phoenix Tuner.

We noticed there was a segmentation fault, and to locate the issue, we commented out the code to start with a basic robot.py file. In the robot init, we initialize a Talon. That by itself results in no segmentation fault. We added `motor.setNeutralMode(NeutralMode.Brake)`, and that was all it took to produce the segmentation fault.

Here is the segmentation fault trace:

![segfault](https://user-images.githubusercontent.com/3255259/150240418-1b44e7af-9aea-45a7-a5cb-4f659f42124f.jpg)

### Operating System

RoboRIO

### Reproducible example code

```text
motor = WPI_TalonFX(0)

motor.setNeutralMode(NeutralMode.Brake)
```

**Comment by virtuald** [comment]
Can reproduce in simulation also on OSX.

**Comment by virtuald** [comment]
Tried it in C++, works fine, so it must be something on our end. Unfortunately, I'm away from my desktop for the night, so I won't be able to look into this until tomorrow morning. Sorry about that.

**Comment by FRC2539** [comment]
No problem 👍

**Comment by TheTripleV** [comment]
Seems to occur on everything inheriting from BaseTalon. BaseTalon works though.

**Comment by virtuald** [comment]
It's a multple virtual inheritance thing... I've got tests duplicating the issue at https://github.com/robotpy/robotpy-build/pull/156
