### ISSUE TITLE
Phoenix Pro support

### ISSUE THREAD

**Issue by virtuald** [robotpy/robotpy-ctre#154]
It's likely that my team won't pay for Phoenix Pro, so I'm not personally planning on implementing support for this.

Happy to accept PRs for Phoenix Pro support if someone else cares about it.

**Comment by virtuald** [comment]
CTRE has released their own Phoenix6 python library this year, so not needed anymore.

**Comment by TheTripleV** [comment]
phoenix6 is available at https://pypi.org/project/phoenix6/ - package name (`phoenix6`) or `robotpy[phoenix6]`

Documentation from CTRE is at https://v6.docs.ctr-electronics.com/en/latest/
