### ISSUE TITLE
Prevent installing simulation stuff on roborio

### ISSUE THREAD

**Issue by virtuald** [robotpy/robotpy-ctre#16]
If you install robotpy-ctre via robotpy-installer, it will cause the simulated hal to be installed on the RoboRIO. We need to prevent that somehow, as it leads to really difficult to debug problems.

**Comment by a2aaron** [comment]
How does one install robotpy-ctre without installing the hal sim?

**Comment by vanjac** [comment]
With the installer, you can use install-opkg instead of install-pip.

`python3 installer.py install-opkg python36-robotpy-ctre`
