### ISSUE TITLE
WPI_TalonSRX.getQuadraturePosition throw not implemented

### ISSUE THREAD

**Issue by a2aaron** [robotpy/robotpy-ctre#23]

**Comment by virtuald** [comment]
Are you using simulation or on the RoboRIO? If so, simulation is not currently supported and that's precisely the error you'll get.

**Comment by a2aaron** [comment]
I'm trying to run tests. I don't have a RoboRIO on me right now, but I'll try deploying to it when I do get access to one.

**Comment by virtuald** [comment]
Yes, if you run tests, it'll fail right now... I felt it was more important to get the hardware stuff out than to wait for sim to be done. Just use `--skip-tests` and it'll deploy.
