### ISSUE TITLE
Argument names do not match in documentation/sim versus on-rio

### ISSUE THREAD

**Issue by nickschatz** [robotpy/robotpy-ctre#37]
Trying to use keyword arguments results in an argument mismatch error on config_kF and configSelectedFeedbackSensor at least, maybe more that I haven't tested. In the documentation the keyword names are given as (in config_kF) slotIdx, value, timeoutMs. On the robot they are arg0, arg1, etc. 

I'll grab the stack trace tomorrow if I can.

**Comment by virtuald** [comment]
That should be easy to fix, forgot about those. Give me a few minutes.

**Comment by virtuald** [comment]
Should be addressed in 2018.1.5
