### ISSUE TITLE
Implement config{Forward,Reverse}LimitSwitchSource

### ISSUE THREAD

**Issue by theopolisme** [robotpy/robotpy-ctre#39]
Thanks so much for fixing #36! Two other methods that would be great to mock would be `configForwardLimitSwitchSource` & `configReverseLimitSwitchSource`. (You can tell we're getting our sensors all hooked up for real instead of just in simulation... 😉)

**Comment by virtuald** [comment]
@theopolisme do you know if `IsFwdLimitSwitchClosed` returns the local switch state or does it return the remote limit switch if configured to use a remote switch?

**Comment by theopolisme** [comment]
Thanks for this! Unfortunately not sure -- we don't have any remote switches set up, they're all just daisy chained off the same srx's. I may be able to take a look tomorrow...
