### ISSUE TITLE
Implement new motion magic stuff

### ISSUE THREAD

**Issue by virtuald** [robotpy/robotpy-ctre#4]
> CANTalonSRX.h has the parameter values. The two eMotMag_ flags. You have to use the scaleVelocityToNativeUnits function on the inputs and then use setParameter to send the value.

**Comment by Twinters007** [comment]
By Sunday

**Comment by virtuald** [comment]
By Sunday?

**Comment by Twinters007** [comment]
I'll try to have this done by Sunday

**Comment by virtuald** [comment]
👍

**Comment by Twinters007** [comment]
I think this is done...

**Comment by auscompgeek** [comment]
Is this done?

**Comment by Twinters007** [comment]
Umm I wanna say yes but I’ll take a look at the jar files and see if I missed anything
