### ISSUE TITLE
1ms Notifier significantly slows down tests

### ISSUE THREAD

**Issue by auscompgeek** [robotpy/robotpy-ctre#45]
Running pyfrc robot tests now end up taking about a minute or so, when they previously finished under 20 seconds.

I think having the simulated PID loop run every 10ms instead (similarly to the simulator) would be more sensible.

**Comment by virtuald** [comment]
@ariovistus would that negatively affect the math?

**Comment by auscompgeek** [comment]
I imagine we would have to compensate for the loop running at a 10th of what it is currently at, but otherwise I imagine it'd positively affect the maths, as the physics.py would be running at the same rate (and so would be able to react to the PID loop in a timely manner).

**Comment by ariovistus** [comment]
a 10ms pid takes different parameters as a 1ms loop for equivalent functionality. I don't know how to predict what the difference would be, or even if it's possible.

**Comment by auscompgeek** [comment]
Given that the simulator will only update every ~10ms, a 1ms PID loop won't respond correctly in the simulator anyway.

**Comment by auscompgeek** [comment]
Update: with the game data cycler and all (9) our autonomous modes, my team's autonomous tests (and _only_ the autonomous tests) now take over 12 minutes in total to run on my laptop. (By my calculations, this means our auto tests take longer than real time!)

The usual pyfrc tests, minus the auto tests (so test_disabled, test_operator_control, test_practice, test_fuzz), take about a minute on my laptop.

**Comment by ariovistus** [comment]
does 

```
ctre.WPI_TalonSRX.Notifier = None
```

help any?

**Comment by vanjac** [comment]
We had to disable the notifier because it was causing the simulator to run very slowly and sometimes freeze.

**Comment by auscompgeek** [comment]
FYI for anyone else who needs to disable the Talon PID simulation, set the `_use_notifier` attribute on the TalonSRX object to `False`.

**Comment by auscompgeek** [comment]
Thinking a bit about how we could go about fixing this, it'd be good to have a way for plugins to hook into the pyfrc physics loop for predictability.

**Comment by auscompgeek** [comment]
OBE with the scrapping of our simulation.
