### ISSUE TITLE
Implement MotionProfile stuff in simulation

### ISSUE THREAD

**Issue by ArchdukeTim** [robotpy/robotpy-ctre#51]
- [ ] configMotionProfileTrajectoryPeriod
- [ ] pushMotionProfileTrajectory
- [ ] processMotionProfileBuffer
- [ ] clearMotionProfileTrajectories

**Comment by AndrewLester** [comment]
pushMotionProfileTrajectory and processMotionProfileBuffer both raise notImplemented errors I believe.

**Comment by auscompgeek** [comment]
I'd be surprised if anything related to motion profiling mode _is_ implemented in simulation.

**Comment by twinters007** [comment]
Well it's annoying that tests fail because things aren't implemented. I don't see why that part is in there

**Comment by auscompgeek** [comment]
OBE with our dependency on CTRE's simulation.
