### ISSUE TITLE
Simulation doesn't allow different devices with same "device ID"

### ISSUE THREAD

**Issue by auscompgeek** [robotpy/robotpy-ctre#70]
For example, this only shows a single CAN motor, even though they have different arbitration IDs:

```python
import ctre
import wpilib


class Robot(wpilib.TimedRobot):
    def robotInit(self):
        self.talon = ctre.WPI_TalonSRX(0)
        self.victor = ctre.WPI_VictorSPX(0)


if __name__ == "__main__":
    wpilib.run(Robot)
```

**Comment by virtuald** [comment]
If you do this in a real system, won't they conflict?

**Comment by auscompgeek** [comment]
No, they have different arbitration IDs.

**Comment by auscompgeek** [comment]
Thinking about the best way to do this, I realised that doing this nicely might involve changes to pyfrc, maybe. Unsure.

**Comment by auscompgeek** [comment]
OBE with the scrapping of our simulation.
