### ISSUE TITLE
CANTalon ControlMode.Follower mode in pyfrc tests

### ISSUE THREAD

**Issue by ruwix** [robotpy/robotpy-ctre#79]
Whenever setting ControlMode.Follower, the pyfrc tests fail with a KeyError.

**Comment by auscompgeek** [comment]
I can't say my team has encountered this issue... can you provide some code to reproduce this issue?

**Comment by ruwix** [comment]
This actually appears to be an issue with our team's code, as I cannot reproduce the error, so for now I am closing the issue

**Comment by virtuald** [comment]
@ruwix if you run into this again, providing a stack trace would be quite helpful.
